apiVersion: v1
kind: Secret
metadata:
    name: riskoptimizer-secrets
type: Opaque
data:
    database-url: bXlzcWw6Ly9hcHB1c2VyOnBhc3N3b3JkQHJpc2tvcHRpbWl6ZXItZGF0YWJhc2U6MzMwNi9yaXNrb3B0aW1pemVyZGI=
    jwt-secret: bXktand0LXNlY3JldC1rZXk=
    mysql-root-password: cm9vdHBhc3N3b3Jk
    mysql-password: cGFzc3dvcmQ=
    api-key: bXktYXBpLWtleQ==
