apiVersion: v1
kind: ConfigMap
metadata:
  name: riskoptimizer-config
data:
  API_URL: "http://riskoptimizer-backend"
  REDIS_HOST: "riskoptimizer-redis"
  REDIS_PORT: "6379"
  DATABASE_HOST: "riskoptimizer-database"
  DATABASE_PORT: "3306"
  DATABASE_NAME: "riskoptimizerdb"
  DATABASE_USER: "appuser"
  LOG_LEVEL: "info"
